### ISSUE TITLE
Unable to find the list of potential features

### ISSUE THREAD

**Issue by Kamariw95** [mlratino/projectCare#1]
Hey -- I know we discussed a list of the features that I could work off of. 

Is that in this repository or another?

**Comment by mlratino** [comment]
hey Kam this is Gino...working at Maria's...it's been a minute, hope all is well with you and yours...thanks for working with us. Here's the link to what you and Maria had discussed before, i believe...
https://github.com/users/mlratino/projects/1

**Comment by Kamariw95** [comment]
Hey Gino! Glad to hear from you. I hope all is well with you too.

I clicked the link and I get a 404 - Page not found. Try sending over the public link. Certain links in Github are only available for the signed in person. In this case, @mlratino is the only one that can see what's at that link. To link me to a project, go to the repository itself (ie. github.com/mlratino/projectCare for example) and send the link over. 

Let me know if you have any questions. Best!

**Comment by mlratino** [comment]
I added some more features.

**Comment by mlratino** [comment]
I am going to try to see if I can include Gino today.
